### ISSUE TITLE
sao không đăng nhập được bác nhỉ, điẹn thoại, fb hay gmail cũng k đc 

### ISSUE THREAD

**Issue by locxeu** [princ3od/Ajent#25]

**Comment by princ3od** [comment]
Hi bác,
Không biết bác clone project về rồi build ra hay cài file apk vậy nhỉ?
Nếu bác clone project về rồi build thì bác phải config project trên Firebase rồi tải và thay thế file google-services.json trong project thì mới có thể đăng nhập được. 
Chủ yếu là config Firebase Authentication, bác có thể tham khảo thử các bài hướng dẫn trên mạng. ^^

**Comment by locxeu** [comment]
ok bác nhé, để e thử
